export const CURSORS = [
  {
    id: 'material-blue-1',
    name: 'Material Blue',
    description: 'Sleek and classic modern design.',
    previewImage: '/cursors/material-blue-1/normal_blue.cur',
    defaultCursor: '/cursors/material-blue-1/normal_blue.cur',
    pointerCursor: '/cursors/material-blue-1/link_blue.gif',
    requirementText: 'Default Unlocked',
    taskKey: null,
  },
  {
    id: 'spray-paint',
    name: 'Spray Paint',
    description: 'Designed for street art creators.',
    previewImage: '/cursors/spray-paint/SPNormal.cur',
    defaultCursor: '/cursors/spray-paint/SPNormal.cur',
    pointerCursor: '/cursors/spray-paint/SPlink.cur',
    requirementText: 'Click "Paint & Contribute"',
    taskKey: 'hasVisitedPaint',
  },
  {
    id: 'advanced',
    name: 'Advanced Reticle',
    description: 'High-precision inspection crosshair.',
    previewImage: '/cursors/advanced/Gun Cursor Advanced.cur',
    defaultCursor: '/cursors/advanced/Gun Cursor Advanced.cur',
    pointerCursor: '/cursors/advanced/Link.gif',
    requirementText: 'Expand artwork modal',
    taskKey: 'hasExpandedModal',
  },
  {
    id: 'flames',
    name: 'Blazing Flames',
    description: 'Fire cursor unlocked by gathering color palettes.',
    previewImage: '/cursors/flames/Arrow.cur',
    defaultCursor: '/cursors/flames/Arrow.cur',
    pointerCursor: '/cursors/flames/Hand.cur',
    requirementText: 'Copy 5 color codes',
    taskKey: 'copiedPaletteCount',
    targetCount: 5,
  },
  {
    id: 'minecraft-diamond-edition',
    name: 'Diamond Sword',
    description: 'Unlocked by exploring canvas history.',
    previewImage: '/cursors/minecraft-diamond-edition/01 Normal Select.png',
    defaultCursor: '/cursors/minecraft-diamond-edition/01 Normal Select.png',
    pointerCursor: '/cursors/minecraft-diamond-edition/15 Link Select.png',
    requirementText: 'Explore 3 different days',
    taskKey: 'daysBrowsedCount',
    targetCount: 3,
  },
  {
    id: 'hello-kitty',
    name: 'Hello Kitty',
    description: 'Bonus cute theme unlocked by master color collectors.',
    previewImage: '/cursors/hello-kitty/Hello Kitty normal select.cur',
    defaultCursor: '/cursors/hello-kitty/Hello Kitty normal select.cur',
    pointerCursor: '/cursors/hello-kitty/Hello Kitty link select.gif',
    requirementText: 'Copy 10 color codes',
    taskKey: 'copiedPaletteCount',
    targetCount: 10,
  },
];